#!/usr/bin/env sh

# check for sudo
if [ $(id -u) != 0 ] ; then
  echo Not root, exiting
  exit
fi

# Simple check for arguments
if [ "$1" != "" ] && [ "$1" != "m" ] && [ "$1" != "s" ]; then
  echo Wrong argument, $1
  echo Usage: u \[\|m\|s\]
  exit
fi

# read date, check if a week has passed and run reflector if necessary
LASTRUNFILE="/usr/local/sbin/lastmirrorupd"

if [ -f "$LASTRUNFILE" ]; then
  LASTUPD=$(cat $LASTRUNFILE)
else
  LASTUPD=$((($(date -d 2000-01-01 +%s)/86400)))
fi

DSLASTUPD=$((($(date +%s)/86400 - $LASTUPD)))

if [ "$1" != "s" ] && [ $DSLASTUPD -gt 60 ] || [ "$1" = "m" ];
then
  echo $DSLASTUPD days since last mirror update
  read -p "Update mirrorlist? [y/N] " -r
  typeset -l REPLY
  if [ "$REPLY" = "yes" ] || [ "$REPLY" = "y" ];
  then
    reflector --score 50 -c it,ch,hr,fr,de,at,es,sk,nl,cz,hu -a 24 -f 10 --sort rate --save /etc/pacman.d/mirrorlist
    echo $((($(date +%s)/86400))) > $LASTRUNFILE
    echo Done.
    echo 'pacman -Syy archlinux-keyring && pacman -Su'
    pacman -Syy archlinux-keyring && pacman -Su
  else
    echo 'pacman -Sy archlinux-keyring && pacman -Syu'
    pacman -Sy archlinux-keyring && pacman -Syu
  fi
else
  echo "Mirrorlist updated less than two months ago."
  echo pacman -Syu
  pacman -Syu
fi

pacdiff -b

paccache -ruk0
paccache -rk1
